### ISSUE TITLE
[Counting] Error

### ISSUE THREAD

**Issue by Menteroth** [elijabesu/SauriCogs#44] opened 2021-01-12 00:18 UTC
```
Ignoring exception in on_message
Traceback (most recent call last):
  File "c:\__\coding\redenv\lib\site-packages\discord\client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "C:\__\coding\Soundwave\cogs\CogManager\cogs\counting\counting.py", line 252, in on_message
    await message.delete()
  File "c:\__\coding\redenv\lib\site-packages\discord\message.py", line 801, in delete
    await self._state.http.delete_message(self.channel.id, self.id)
  File "c:\__\coding\redenv\lib\site-packages\discord\http.py", line 243, in request
    raise NotFound(r, data)
discord.errors.NotFound: 404 Not Found (error code: 10008): Unknown Message
```

**Comment by kreus7** [comment] 2021-02-10 14:24
This is most likely because the message was already deleted previously by the author, someone with permissions, or from another source

**Comment by kreus7** [comment] 2021-02-10 14:29
#45

**Comment by elijabesu** [comment] 2021-02-19 08:35
Please, do let me know if this was fixed with your merge :)

**Comment by Menteroth** [comment] 2021-02-20 18:37
What can I do to test it?

**Comment by kreusada** [comment] 2021-02-20 20:02
It would be very difficult to reproduce given that it was a very rare exception. You'd probably need to find a 3rd party cog or make something yourself that will delete messages in a channel, and then just hope that the message is deleted before counting comes into effect. May be very difficult, I can help you out if you wish. I think the PR should've covered it however, so this issue is probably good to go now.

**Closed** 2021-02-22 07:58 UTC
Labels: bug, feedback needed
